### ISSUE TITLE
ValueError: Found array with 0 feature(s) (shape=(2, 0)) 

### ISSUE THREAD

**Issue by YingUK** [manavkataria/CarND-Vehicle-Detection#3]
Hi, 

thanks for sharing the code.  I have changed all configurations in settings.py, and when I ran main.py, i see below error. Could you help to fix this issue please? @manavkataria 
Error message is : 
ValueError: Found array with 0 feature(s) (shape=(2, 0)) while a minimum of 1 is required by StandardScaler.

Thank you so much!

**Comment by manavkataria** [comment]
@YingHou: I apologize, but I would not be able to support debugging requests given the busyness of my work schedule. The error looks trivial to debug. If you step through the code, I'm sure you would be able to figure this out.
